### ISSUE TITLE
Failure running `run.py`

### ISSUE THREAD

**Issue by stefanseefeld** [boostorg/regression#39]
Following the online docs I downloaded and executed the `run.py` script using

```
python run.py --runner=Stefan --toolsets=gcc-6.2.1 --tag=develop
```

which eventually resulted in

```
# Executing GIT command: /home/stefan/projects/boost_root> git submodule foreach "git submodule deinit ."
Entering 'libs/accumulators'
error: pathspec '.' did not match any file(s) known to git.
Stopping at 'libs/accumulators'; script returned non-zero status.
# git_source_checkout failed with message "GIT command "git submodule foreach "git submodule deinit ."" failed with code 256"
# Retrying (5 more attempts).
...
# Retrying (1 more attempts).
# Executing GIT command: /home/stefan/projects/boost_root> git submodule foreach "git submodule deinit ."
Entering 'libs/accumulators'
error: pathspec '.' did not match any file(s) known to git.
Stopping at 'libs/accumulators'; script returned non-zero status.
# git_source_checkout failed with message "GIT command "git submodule foreach "git submodule deinit ."" failed with code 256"
# Giving up.
Traceback (most recent call last):
  File "run.py", line 71, in <module>
    runner(root)
  File "/home/stefan/projects/boost_regression_src/regression.py", line 287, in __init__
    self.main()
  File "/home/stefan/projects/boost_regression_src/regression.py", line 624, in main
    getattr(self,action_m)()
  File "/home/stefan/projects/boost_regression_src/regression.py", line 579, in command_regression
    self.command_get_source()
  File "/home/stefan/projects/boost_regression_src/regression.py", line 331, in command_get_source
    self.retry(self.git_source_checkout)
  File "/home/stefan/projects/boost_regression_src/regression.py", line 663, in retry
    return f()
  File "/home/stefan/projects/boost_regression_src/regression.py", line 876, in git_source_checkout
    self.git_checkout(git_info['boost'], self.git_branch(), clean)
  File "/home/stefan/projects/boost_regression_src/regression.py", line 847, in git_checkout
    self.git_command( 'submodule foreach', 'git submodule deinit .')
  File "/home/stefan/projects/boost_regression_src/regression.py", line 835, in git_command
    raise Exception( 'GIT command "%s" failed with code %d' % (git_cli, rc) )
Exception: GIT command "git submodule foreach "git submodule deinit ."" failed with code 256
```

**Comment by stefanseefeld** [comment]
I'm using python 2.7.12 and git 2.7.4 on a Fedora 24 machine.

**Comment by stefanseefeld** [comment]
Ping ? I'd really like to help test Boost, but am blocked on the above.

**Comment by stefanseefeld** [comment]
(This works if I downgrade git to 2.1.4)

**Comment by Neargye** [comment]
I had the same error, using python 2.7.12 and git 2.7.4 on ubuntu Ubuntu 16.04.4.

Install git version 2.16.2 like that:
```
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git
```

And the tests run successfully.
It looks like some problem with run test with git version 2.7.4.
